### ISSUE TITLE
LC_ALL no funciona en windows

### ISSUE THREAD

**Issue by agraciakuvut** [buuum/Git#1]
La comanda de git con LC_ALL no funciona en windows, propongo eliminarlo a falta de encontrar alguna alternativa:

`       
 $command = 'LC_ALL=es_ES.UTF-8 git -C ' . escapeshellarg($this->repository_path) . ' ' . $command;
`

`       
 $command = 'git -C ' . escapeshellarg($this->repository_path) . ' ' . $command;
`

**Comment by buuum** [comment]
in version 1.0.1 this bug is solved
